### PR TITLE
Update CI configuration

### PR DESCRIPTION
**Pull request by CAMOBAP**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 this repo is special:
1. It uses `rake test` instead of just `rake`. You need to update Rakefile to make just `rake` work.
2. It does something special with Perl, not sure if we need to do it.
3. It doesn't need Puppeteer.

It is originally all passing, and this PR must all pass to merge.

Can you help update? Thanks.

**Comment by CAMOBAP** [comment]
@ronaldtse 

> 1. It uses rake test instead of just rake. You need to update Rakefile to make just rake work.

Done

> 2. It does something special with Perl, not sure if we need to do it.

As far as I see we need it only for latexml nothing more

> 3. It doesn't need Puppeteer.

Agree, but because it tokes ~10 seconds to install I propose to not create separate CI configuration for tex2mn and reuse existent

**Comment by CAMOBAP** [comment]
Checking tests

**Comment by CAMOBAP** [comment]
@ronaldtse after review I see that configuration too specific, I will close this PR

**Pull request closed without merging**
